# Generated by Django 5.2.7 on 2025-11-17 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='temporada',
            options={'ordering': ['-anyo'], 'verbose_name': 'Temporada', 'verbose_name_plural': 'Temporadas'},
        ),
        migrations.RenameField(
            model_name='equipo',
            old_name='anio_fundacion',
            new_name='fundacion',
        ),
        migrations.RenameField(
            model_name='temporada',
            old_name='anio',
            new_name='anyo',
        ),
    ]
