# Generated by Django 5.2.7 on 2025-11-17 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_temporada_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partido',
            old_name='equipo_local',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='partido',
            old_name='equipo_visitante',
            new_name='visitante',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='aforo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='fundacion',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de fundación'),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_local',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='partido',
            name='goles_visitante',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
