# Generated by Django 5.2.7 on 2025-11-17 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partido',
            old_name='equipo_local',
            new_name='local',
        ),
        migrations.RenameField(
            model_name='partido',
            old_name='equipo_visitante',
            new_name='visitante',
        ),
    ]
