# Generated by Django 5.2.7 on 2025-11-23 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Uva',
            fields=[
                ('idUva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='DenominacionOrigen',
            fields=[
                ('idDenominacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pais')),
            ],
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('idVino', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.denominacionorigen')),
                ('uvas', models.ManyToManyField(to='main.uva')),
            ],
        ),
    ]
