# Generated by Django 5.2.7 on 2025-11-23 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DenominacionOrigen',
            new_name='Denominacion',
        ),
    ]
