# Generated by Django 5.1.4 on 2024-12-17 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='idIMDB',
            field=models.CharField(max_length=50),
        ),
    ]
