# Generated by Django 5.1.4 on 2024-12-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0002_alter_pelicula_idimdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='idIMDB',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='idPelicula',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
