# Generated by Django 5.1.4 on 2024-12-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('peliculas', '0003_alter_pelicula_idimdb_alter_pelicula_idpelicula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puntuacion',
            name='puntuacion',
            field=models.IntegerField(),
        ),
    ]
