# Generated by Django 6.0 on 2025-12-11 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('artistaId', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField(unique=True, verbose_name='Nombre del Artista')),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL del Artista')),
                ('imagen', models.URLField(blank=True, null=True, verbose_name='URL de la Imagen')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('tagId', models.AutoField(primary_key=True, serialize=False)),
                ('tagValue', models.TextField(unique=True, verbose_name='Nombre de la Etiqueta')),
            ],
            options={
                'ordering': ['tagValue'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioArtista',
            fields=[
                ('usuarioId', models.TextField(primary_key=True, serialize=False)),
                ('tiempoEscucha', models.IntegerField(default=0, verbose_name='Tiempo de Escucha (minutos)')),
                ('artistaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artista')),
            ],
            options={
                'ordering': ('usuarioId', 'artistaId'),
            },
        ),
        migrations.CreateModel(
            name='UsuarioEtiquetaArtista',
            fields=[
                ('usuarioId', models.TextField(primary_key=True, serialize=False)),
                ('artistaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artista')),
                ('tagId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.etiqueta')),
            ],
            options={
                'ordering': ('usuarioId', 'artistaId', 'tagId'),
            },
        ),
    ]
