# Generated by Django 6.0 on 2025-12-11 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioartista',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='usuarioetiquetaartista',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usuarioartista',
            name='usuarioId',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='usuarioetiquetaartista',
            name='usuarioId',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='usuarioartista',
            unique_together={('usuarioId', 'artistaId')},
        ),
        migrations.AlterUniqueTogether(
            name='usuarioetiquetaartista',
            unique_together={('usuarioId', 'artistaId', 'tagId')},
        ),
    ]
