# Generated by Django 5.2.7 on 2025-11-23 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('idPais', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Uva',
            fields=[
                ('idUva', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Uva',
                'verbose_name_plural': 'Uvas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Denominacion',
            fields=[
                ('idDenominacion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pais')),
            ],
            options={
                'verbose_name': 'Denominacion',
                'verbose_name_plural': 'Denominaciones',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Vino',
            fields=[
                ('idVino', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
                ('denominacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.denominacion')),
                ('uvas', models.ManyToManyField(blank=True, related_name='vinos', to='main.uva')),
            ],
            options={
                'verbose_name': 'Vino',
                'verbose_name_plural': 'Vinos',
                'ordering': ['nombre'],
            },
        ),
    ]
